const format = (n) => '₹' + n.toLocaleString('en-IN');

export default function FundingBreakdown({ stats }) {
  const laptopCost = stats.laptopCost;
  const raised = stats.totalRaised;
  const remaining = Math.max(0, laptopCost - raised);
  const percent = Math.min(100, Math.round((raised / laptopCost) * 100));

  return (
    <section className="border-b border-white/5 bg-ink">
      <div className="mx-auto max-w-[1400px] px-5 md:px-8 py-24 md:py-32">
        <div className="grid lg:grid-cols-[1fr_1.3fr] gap-14 items-start">
          <div>
            <div className="text-[11px] uppercase tracking-[0.22em] text-muted font-mono mb-4">
              Section 07 · Transparency
            </div>
            <h2 className="display text-[44px] md:text-[72px] leading-[1] tracking-tightest">
              What your money buys.
            </h2>
            <p className="mt-6 text-soft leading-relaxed max-w-[46ch]">
              This isn't some mysterious advertising inventory generated by a
              spreadsheet. Your money is literally helping fund the machine you're
              advertising on.
            </p>
            <p className="mt-4 text-soft leading-relaxed max-w-[46ch]">
              If enough brands buy enough laptop real estate, this machine pays for
              itself. Capitalism has officially become stickers.
            </p>
          </div>

          <div className="rounded-3xl border border-white/5 bg-panel p-6 md:p-10">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="mono text-[10px] uppercase tracking-widest text-muted">Item</div>
                <div className="font-display text-2xl mt-1">ASUS TUF Gaming F15</div>
                <div className="text-xs text-muted mt-1">Demo figures for illustration.</div>
              </div>
              <div className="text-right">
                <div className="mono text-[10px] uppercase tracking-widest text-muted">Retail</div>
                <div className="mono text-2xl mt-1">{format(laptopCost)}</div>
              </div>
            </div>

            <div className="mt-8">
              <div className="flex items-baseline justify-between mb-2">
                <span className="mono text-sm">{format(raised)} raised</span>
                <span className="mono text-sm text-muted">{percent}%</span>
              </div>
              <div className="h-3 rounded-full bg-raised overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-acid to-acidDim transition-all duration-700"
                  style={{ width: `${percent}%` }}
                />
              </div>
              <div className="mt-2 text-xs text-muted">
                {stats.sold} / {stats.spotsTotal} spots claimed
              </div>
            </div>

            <div className="mt-8 divide-y divide-white/5">
              <Row label="Laptop retail" value={format(laptopCost)} />
              <Row label="Total sponsor contribution" value={format(raised)} accent />
              <Row label="Remaining amount" value={format(remaining)} />
              <Row label="Sponsors on the lid" value={String(stats.sold)} />
              <Row label="Payment status" value="Held in demo escrow" muted />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Row({ label, value, muted, accent }) {
  return (
    <div className="flex items-center justify-between py-3">
      <div className={`text-sm ${muted ? 'text-muted' : 'text-soft'}`}>{label}</div>
      <div className={`mono ${accent ? 'text-acid' : muted ? 'text-muted' : 'text-chalk'}`}>{value}</div>
    </div>
  );
}
